compile: 
	rm -rf build/
	mkdir build
	$ D:\jdk1.5.0_22\bin\javac -Xlint:-options -source 1.5 -target 1.5 -cp lib\joeq.jar -sourcepath src -d build `find src -name "*.java"`
	 D:\\jdk1.5.0_22\\bin\\javac -Xlint:-options -source 1.5 -target 1.5 	-cp lib\\joeq.jar	-sourcepath src -d build `find src -name "*.java"`